Make plants use fertilizers described with json.
AgriCraft/AgriCraft pull request #1380
Opened 2021-07-11 20:12 UTC by nbrichau

This PR is the implementation of #750.
I replaced the fertilizer adapterizer with a fertilizer registry.
I also did some changes the api to use the new fertilizers.

I took inspiration of the way soils are registered to register the fertilizers. Hopefully I did it the right way.

2021-07-14 14:14 UTC, InfinityRaider requested changes
Looks good overall, the only thing I am not sure about is the phasing out of the Adapterizer, in favor of a Provider, which are, functionally almost identical, except that the latter is more restrictive.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizer.java
>  public interface IAgriFertilizer extends IAgriRegisterable<IAgriFertilizer> {
I am not 100% on the modifications here.
Functionally, the IAgriFertilizer has not changed, only the internal AgriCraft implementation.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizer.java
> +    String getId();
Redundant.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizer.java
> +    Collection<Item> getVariants();
This is not needed.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizer.java
> +    int getPotency();
This is relevant for AgriCraft's implementation only, not for the abstract represenation of fertilizers.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizerProvider.java
> +public interface IAgriFertilizerProvider {
Why do you phase out the Fertilizerr Adapterizer, but then introduce a Provider, which is functionally the same thing?

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizerRegistry.java
> +    IAgriFertilizerProvider getProvider(@Nonnull Item item);
Not quite sure about the necessity of this.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/CoreHandler.java
> +        // See if soils are valid...
I suppose this is a ctrl+c / ctrl+v artefact?

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/CoreHandler.java
> +        // Display Soils
Ditto

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/AgriFertilizerRegistry.java
> +    private final Map<Item, IAgriFertilizerProvider> providers;
Instead of a map, we could keep the Adapterizer here, this does not restrict to Item -> fertilizer bijections, allowing for NBT-sensitive stuff as well.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/AgriFertilizerRegistry.java
> +        return NO_FERTILIZER != element && super.remove(element);
Good.

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +        // to spawn the bone meal particles
Shouldn't this use the json's particles now?

2021-07-14 14:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +        return ActionResultType.SUCCESS;
I believe the negative effect is missing?

2021-07-14 20:00 UTC, nbrichau commented
I think all the changes needed are done. Some notable things since your review are :
- I replaced the fertilizer registry with the adapterizer.
- I removed the NoFertilizer (I don't see why it's usefull now that I use an adapterizer).
- I removed `IAgriPlant#isFertilizable`. I hesitated to deprecated the method, but because it isn't used anywhere in the code I removed it.
- `IAgriFertilizable#acceptsFertilizer` is now unused in the code. Every call are replaced by `IAgriFertilizer#canFertilize`.

2021-07-15 11:14 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +                        if (current.equals(previous)) {
Unsure whether or not to move the negative effect outside the loop 
For the positive effect it makes sense, as not every growth tick is guaranteed to pass 
The negative effect is however applied every pass, so I feel the negative effect is disproportionately more powerful than the positive one.

2021-07-15 11:37 UTC, nbrichau commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +                        if (current.equals(previous)) {
I think that more a fertilizer is powerful, more its negative effect should be powerful, and easier it gets to kill the plant.
The negative effect have half a chance to be applied (L 83 : `&& random.nextBoolean()`). So I don't think it's that disproportionate, but I could change the probability to 1/3 or 1/4.

2021-07-15 13:52 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +                        if (current.equals(previous)) {
Ah I see, I must have read over that random check.

2021-07-15 14:00 UTC, nbrichau commented
I figured that this was a bad decision, and some checks are made in `IAgriFertilizable#acceptsFertilizer` (in agricraft's implementation) that wheren't done after I changed that.

2021-07-15 14:23 UTC, InfinityRaider requested changes

2021-07-15 14:23 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/fertilizer/IAgriFertilizer.java
> +public interface IAgriFertilizer extends IAgriRegisterable<IAgriFertilizer>, IAgriAdapter<IAgriFertilizer> {
Is the IAfriRegistrable still needed?

2021-07-15 14:23 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/api/v1/plant/IAgriPlant.java
> -
This should be kept and called.

2021-07-15 14:23 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/content/core/TileEntityCropBase.java
>          } else {
Needs to call the plant method as well.

2021-07-15 14:23 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +            if (target instanceof IAgriCrop && ((IAgriCrop) target).hasPlant()) {
Tthe hasPlant() check will prevent fertilizer usage on cross crops to force mutations.

2021-07-15 14:23 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +        return ((IAgriCrop) target).hasPlant() && this.fertilizerEffect.canFertilize(((IAgriCrop) target).getPlant().getId());
What about fertilizing cross crops to force mutations?

2021-07-15 14:23 UTC, InfinityRaider commented on src/main/java/com/infinityraider/agricraft/impl/v1/fertilizer/JsonFertilizer.java
> +            return;
I don't like this cast at each time but there isn't really a way around it with how we have the json set up....

2021-07-19 09:13 UTC, merged